package httpapi

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"image"
	"image/png"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/auucoder/gptgrok2api-go/internal/provider"
)

// Exercise the public routes against a ChatGPT-shaped upstream. In particular,
// accepting the catalog ID alone is insufficient: prepare and generation must
// both send a conversation model and retain the picture tool and attachments.
func TestGPTImage25Endpoints(t *testing.T) {
	var generated bytes.Buffer
	if err := png.Encode(&generated, image.NewRGBA(image.Rect(0, 0, 2, 2))); err != nil {
		t.Fatal(err)
	}
	generatedPNG := generated.Bytes()
	referenceURL := "data:image/png;base64," + base64.StdEncoding.EncodeToString(tinyPNG)
	for _, tc := range []struct {
		name          string
		path          string
		model         string
		upstreamModel string
		format        string
		count         int
		references    int
		multipart     bool
		stream        bool
	}{
		{"generation_url", "/v1/images/generations", "gpt-image-2.5", "auto", "url", 2, 0, false, false},
		{"generation_base64", "/v1/images/generations", "gpt-image-2.5", "auto", "b64_json", 1, 0, false, false},
		{"edit_json", "/v1/images/edits", "gpt-image-2.5", "auto", "url", 1, 2, false, false},
		{"edit_multipart", "/v1/images/edits", "gpt-image-2.5", "auto", "url", 1, 1, true, false},
		{"chat_text", "/v1/chat/completions", "gpt-image-2.5", "auto", "", 1, 0, false, false},
		{"chat_reference", "/v1/chat/completions", "gpt-image-2.5", "auto", "", 1, 1, false, false},
		{"chat_stream", "/v1/chat/completions", "gpt-image-2.5", "auto", "", 1, 0, false, true},
		{"legacy_generation", "/v1/images/generations", "gpt-image-2", "gpt-5-3", "url", 1, 0, false, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			const generatedID = "file_00000000999999999999999999999999"
			var uploads, prepares, generations atomic.Int32
			var upstream *httptest.Server
			upstream = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				if strings.HasPrefix(r.URL.Path, "/backend-api/") && r.Header.Get("Authorization") != "Bearer jwt.header.payload" {
					t.Errorf("wrong account selected for %s", r.URL.Path)
					http.Error(w, "wrong account", http.StatusUnauthorized)
					return
				}
				switch {
				case r.URL.Path == "/":
					w.Header().Set("Content-Type", "text/html")
					_, _ = io.WriteString(w, "<html data-build=\"test-build\"></html>")
				case r.URL.Path == "/backend-api/sentinel/chat-requirements/prepare":
					_ = json.NewEncoder(w).Encode(map[string]any{"prepare_token": "prepare-token"})
				case r.URL.Path == "/backend-api/sentinel/chat-requirements/finalize":
					_ = json.NewEncoder(w).Encode(map[string]any{"token": "requirements-token"})
				case r.URL.Path == "/backend-api/files":
					id := fmt.Sprintf("file_%032d", uploads.Add(1))
					_ = json.NewEncoder(w).Encode(map[string]any{"file_id": id, "upload_url": upstream.URL + "/upload/" + id})
				case strings.HasPrefix(r.URL.Path, "/upload/"):
					raw, _ := io.ReadAll(r.Body)
					if r.Method != http.MethodPut || !bytes.Equal(raw, tinyPNG) {
						t.Errorf("reference image was not uploaded intact")
					}
					w.WriteHeader(http.StatusCreated)
				case strings.HasSuffix(r.URL.Path, "/uploaded"):
					_, _ = io.WriteString(w, "{}")
				case r.URL.Path == "/backend-api/f/conversation/prepare" || r.URL.Path == "/backend-api/f/conversation":
					var payload map[string]any
					if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
						t.Errorf("invalid upstream JSON: %v", err)
						http.Error(w, "invalid JSON", http.StatusBadRequest)
						return
					}
					hints, _ := payload["system_hints"].([]any)
					if payload["model"] != tc.upstreamModel || len(hints) != 1 || hints[0] != "picture_v2" {
						t.Errorf("wrong conversation route: model=%v hints=%v", payload["model"], hints)
						http.Error(w, "invalid image conversation route", http.StatusBadRequest)
						return
					}
					if strings.HasSuffix(r.URL.Path, "/prepare") {
						prepares.Add(1)
						_ = json.NewEncoder(w).Encode(map[string]any{"conduit_token": "conduit-token"})
						return
					}
					generations.Add(1)
					messages, _ := payload["messages"].([]any)
					if len(messages) != 1 {
						t.Errorf("expected one image prompt, got %d", len(messages))
						http.Error(w, "missing image prompt", http.StatusBadRequest)
						return
					}
					message, _ := messages[0].(map[string]any)
					metadata, _ := message["metadata"].(map[string]any)
					attachments, _ := metadata["attachments"].([]any)
					messageHints, _ := metadata["system_hints"].([]any)
					if len(attachments) != tc.references || len(messageHints) != 1 || messageHints[0] != "picture_v2" {
						t.Errorf("lost image metadata: %v", metadata)
					}
					echoID := generatedID
					if tc.references > 0 {
						echoID = "file_00000000000000000000000000000001"
					}
					w.Header().Set("Content-Type", "text/event-stream")
					_, _ = fmt.Fprintf(w, "data: {\"conversation_id\":\"image-25\",\"message\":{\"content\":{\"parts\":[\"file-service://%s\"]}}}\n\ndata: [DONE]\n\n", echoID)
				case r.URL.Path == "/backend-api/conversation/image-25":
					writeHTTPAPIGeneratedImageConversation(w, generatedID)
				case r.URL.Path == "/backend-api/files/"+generatedID+"/download":
					_ = json.NewEncoder(w).Encode(map[string]any{"download_url": upstream.URL + "/blob"})
				case r.URL.Path == "/blob":
					w.Header().Set("Content-Type", "image/png")
					_, _ = w.Write(generatedPNG)
				default:
					t.Errorf("unexpected upstream request: %s %s", r.Method, r.URL.Path)
					http.NotFound(w, r)
				}
			}))
			defer upstream.Close()

			root := t.TempDir()
			cfg := testConfig()
			cfg.RootDir, cfg.DataDir = root, root
			cfg.ConfigPath = filepath.Join(root, "config.json")
			cfg.AccountsPath = filepath.Join(root, "accounts.json")
			cfg.AuthKeysPath = filepath.Join(root, "auth_keys.json")
			cfg.ImageDataDir = filepath.Join(root, "images")
			server := New(cfg)
			server.openAIImage = provider.NewOpenAIImage(upstream.URL, upstream.Client(), nil, 5*time.Second)
			if _, _, _, err := server.store.AddAccounts(nil, []map[string]any{
				{"access_token": "jwt.header.payload", "source_type": "chatgpt_web", "pool": "basic"},
				{"token": "grok-cookie", "source_type": "grok", "pool": "super"},
			}); err != nil {
				t.Fatal(err)
			}

			body := map[string]any{
				"model": tc.model, "prompt": "draw a cat", "n": tc.count,
				"size": "864x1152", "response_format": tc.format,
			}
			refs := make([]string, tc.references)
			for i := range refs {
				refs[i] = referenceURL
			}
			if tc.references > 0 {
				body["image_url"] = refs
			}
			if tc.path == "/v1/chat/completions" {
				var content any = "draw a cat"
				if tc.references > 0 {
					content = []any{
						map[string]any{"type": "text", "text": "draw a cat"},
						map[string]any{"type": "image_url", "image_url": map[string]any{"url": referenceURL}},
					}
				}
				body = map[string]any{"model": tc.model, "stream": tc.stream, "messages": []any{map[string]any{"role": "user", "content": content}}}
			}
			var requestBody bytes.Buffer
			contentType := "application/json"
			if tc.multipart {
				writer := multipart.NewWriter(&requestBody)
				for key, value := range map[string]string{"model": tc.model, "prompt": "draw a cat", "size": "864x1152"} {
					if err := writer.WriteField(key, value); err != nil {
						t.Fatal(err)
					}
				}
				part, err := writer.CreateFormFile("image", "reference.png")
				if err != nil {
					t.Fatal(err)
				}
				if _, err := part.Write(tinyPNG); err != nil {
					t.Fatal(err)
				}
				if err := writer.Close(); err != nil {
					t.Fatal(err)
				}
				contentType = writer.FormDataContentType()
			} else if err := json.NewEncoder(&requestBody).Encode(body); err != nil {
				t.Fatal(err)
			}
			request := httptest.NewRequest(http.MethodPost, tc.path, &requestBody)
			request.Header.Set("Content-Type", contentType)
			request.Header.Set("Authorization", "Bearer api-secret")
			response := httptest.NewRecorder()
			server.Handler().ServeHTTP(response, request)
			if response.Code != http.StatusOK {
				t.Fatalf("unexpected response: %d %s", response.Code, response.Body.String())
			}
			if prepares.Load() != int32(tc.count) || generations.Load() != int32(tc.count) || uploads.Load() != int32(tc.references*tc.count) {
				t.Fatalf("unexpected pipeline calls: prepare=%d generate=%d upload=%d", prepares.Load(), generations.Load(), uploads.Load())
			}
			if tc.path == "/v1/chat/completions" {
				if !strings.Contains(response.Body.String(), "![image](") || !strings.Contains(response.Body.String(), "\"model\":\""+tc.model+"\"") {
					t.Fatalf("missing image chat output: %s", response.Body.String())
				}
				if tc.stream && (!strings.HasPrefix(response.Header().Get("Content-Type"), "text/event-stream") || !strings.Contains(response.Body.String(), "data: [DONE]")) {
					t.Fatalf("invalid image chat stream: %s", response.Body.String())
				}
				return
			}
			var result struct{ Data []map[string]string }
			if err := json.Unmarshal(response.Body.Bytes(), &result); err != nil {
				t.Fatal(err)
			}
			if len(result.Data) != tc.count {
				t.Fatalf("expected %d images, got %d", tc.count, len(result.Data))
			}
			for _, item := range result.Data {
				if tc.format == "b64_json" {
					raw, err := base64.StdEncoding.DecodeString(item["b64_json"])
					if err != nil || !bytes.Equal(raw, generatedPNG) {
						t.Fatalf("base64 result is not the generated image")
					}
				} else {
					if !strings.Contains(item["url"], "/v1/files/image?id=") {
						t.Fatalf("missing local image URL: %v", item)
					}
					file := httptest.NewRecorder()
					server.Handler().ServeHTTP(file, httptest.NewRequest(http.MethodGet, item["url"], nil))
					if file.Code != http.StatusOK || !bytes.Equal(file.Body.Bytes(), generatedPNG) {
						t.Fatalf("stored result is not the generated image: %d", file.Code)
					}
				}
			}
		})
	}
}
